# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_reservations.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
from table_dialog import Ui_Dialog
from warning import Ui_Dialog2
from reserver_data import Ui_Dialog3

class Table:
    def __init__(self, number, status, no_of_chairs):
        self.number = number
        self.status = status
        self.no_of_chairs = no_of_chairs
    reserver_name = ''
    reserver_phone = ''


class Table_Rerservation(object):
    font = QtGui.QFont()
    font.setFamily("MS Shell Dlg 2")
    font.setPointSize(14)
    font.setBold(False)
    font.setWeight(75)
    text_label = []
    reserve_push_buttons = []
    un_reserve_push_buttons = []
    table_info_push_buttons = []
    tables = [Table(1, 'Not Reserved', 2), Table(2, 'Not Reserved', 2), Table(3, 'Not Reserved', 2),
              Table(4, 'Not Reserved', 4), Table(5, 'Not Reserved', 4),
              Table(6, 'Not Reserved', 4), Table(7, 'Not Reserved', 6), Table(8, 'Not Reserved', 6),
              Table(9, 'Not Reserved', 10)]
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 566)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("restaurant-table.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout.addWidget(self.pushButton_21)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_11.addWidget(self.pushButton_12)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_11.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("restaurant-table.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_12.addWidget(self.pushButton_15)
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_12.addWidget(self.pushButton_22)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.gridLayout.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("restaurant-table.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_18 = QtWidgets.QLabel(self.groupBox_7)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_7.addWidget(self.label_18)
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_7.addWidget(self.pushButton_23)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_13.addWidget(self.pushButton_20)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_13.addWidget(self.pushButton_7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.gridLayout.addWidget(self.groupBox_7, 0, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("restaurant-table.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_14.addWidget(self.pushButton_13)
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_14.addWidget(self.pushButton_24)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("restaurant-table.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_5.addWidget(self.pushButton_5)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_17.addWidget(self.pushButton_16)
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_17.addWidget(self.pushButton_29)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.gridLayout.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("restaurant-table.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_17 = QtWidgets.QLabel(self.groupBox_8)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_8.addWidget(self.label_17)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_8.addWidget(self.pushButton_8)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_18.addWidget(self.pushButton_19)
        self.pushButton_28 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_18.addWidget(self.pushButton_28)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_8.addLayout(self.verticalLayout_8)
        self.gridLayout.addWidget(self.groupBox_8, 1, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("restaurant-table.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_15.addWidget(self.pushButton_14)
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_15.addWidget(self.pushButton_25)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("restaurant-table.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_6.addWidget(self.pushButton_6)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_16.addWidget(self.pushButton_17)
        self.pushButton_26 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_16.addWidget(self.pushButton_26)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.gridLayout.addWidget(self.groupBox_6, 2, 1, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("restaurant-table.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.groupBox_9)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_9.addWidget(self.label_16)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_9.addWidget(self.pushButton_9)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_19.addWidget(self.pushButton_18)
        self.pushButton_27 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_19.addWidget(self.pushButton_27)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        self.gridLayout.addWidget(self.groupBox_9, 2, 2, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_10.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_10.addWidget(self.pushButton_11)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.text_label.append(self.label_10)
        self.text_label.append(self.label_15)
        self.text_label.append(self.label_18)
        self.text_label.append(self.label_11)
        self.text_label.append(self.label_14)
        self.text_label.append(self.label_17)
        self.text_label.append(self.label_12)
        self.text_label.append(self.label_13)
        self.text_label.append(self.label_16)
        self.reserve_push_buttons.append(self.pushButton_12)
        self.reserve_push_buttons.append(self.pushButton_15)
        self.reserve_push_buttons.append(self.pushButton_20)
        self.reserve_push_buttons.append(self.pushButton_13)
        self.reserve_push_buttons.append(self.pushButton_16)
        self.reserve_push_buttons.append(self.pushButton_19)
        self.reserve_push_buttons.append(self.pushButton_14)
        self.reserve_push_buttons.append(self.pushButton_17)
        self.reserve_push_buttons.append(self.pushButton_18)

        self.un_reserve_push_buttons.append(self.pushButton)
        self.un_reserve_push_buttons.append(self.pushButton_22)
        self.un_reserve_push_buttons.append(self.pushButton_7)
        self.un_reserve_push_buttons.append(self.pushButton_24)
        self.un_reserve_push_buttons.append(self.pushButton_29)
        self.un_reserve_push_buttons.append(self.pushButton_28)
        self.un_reserve_push_buttons.append(self.pushButton_25)
        self.un_reserve_push_buttons.append(self.pushButton_26)
        self.un_reserve_push_buttons.append(self.pushButton_27)

        self.table_info_push_buttons.append(self.pushButton_21)
        self.table_info_push_buttons.append(self.pushButton_4)
        self.table_info_push_buttons.append(self.pushButton_23)
        self.table_info_push_buttons.append(self.pushButton_2)
        self.table_info_push_buttons.append(self.pushButton_5)
        self.table_info_push_buttons.append(self.pushButton_8)
        self.table_info_push_buttons.append(self.pushButton_3)
        self.table_info_push_buttons.append(self.pushButton_6)
        self.table_info_push_buttons.append(self.pushButton_9)


        self.retranslateUi(MainWindow)
        # dont know how to avoid this when putting in loop only the last button response
        self.reserve_push_buttons[0].clicked.connect(lambda: self.reserve_table(self.tables[0], self.text_label[0]))
        self.reserve_push_buttons[1].clicked.connect(lambda: self.reserve_table(self.tables[1], self.text_label[1]))
        self.reserve_push_buttons[2].clicked.connect(lambda: self.reserve_table(self.tables[2], self.text_label[2]))
        self.reserve_push_buttons[3].clicked.connect(lambda: self.reserve_table(self.tables[3], self.text_label[3]))
        self.reserve_push_buttons[4].clicked.connect(lambda: self.reserve_table(self.tables[4], self.text_label[4]))
        self.reserve_push_buttons[5].clicked.connect(lambda: self.reserve_table(self.tables[5], self.text_label[5]))
        self.reserve_push_buttons[6].clicked.connect(lambda: self.reserve_table(self.tables[6], self.text_label[6]))
        self.reserve_push_buttons[7].clicked.connect(lambda: self.reserve_table(self.tables[7], self.text_label[7]))
        self.reserve_push_buttons[8].clicked.connect(lambda: self.reserve_table(self.tables[8], self.text_label[8]))

        self.un_reserve_push_buttons[0].clicked.connect(lambda: self.un_reserve_table(self.tables[0], self.text_label[0]))
        self.un_reserve_push_buttons[1].clicked.connect(lambda: self.un_reserve_table(self.tables[1], self.text_label[1]))
        self.un_reserve_push_buttons[2].clicked.connect(lambda: self.un_reserve_table(self.tables[2], self.text_label[2]))
        self.un_reserve_push_buttons[3].clicked.connect(lambda: self.un_reserve_table(self.tables[3], self.text_label[3]))
        self.un_reserve_push_buttons[4].clicked.connect(lambda: self.un_reserve_table(self.tables[4], self.text_label[4]))
        self.un_reserve_push_buttons[5].clicked.connect(lambda: self.un_reserve_table(self.tables[5], self.text_label[5]))
        self.un_reserve_push_buttons[6].clicked.connect(lambda: self.un_reserve_table(self.tables[6], self.text_label[6]))
        self.un_reserve_push_buttons[7].clicked.connect(lambda: self.un_reserve_table(self.tables[7], self.text_label[7]))
        self.un_reserve_push_buttons[8].clicked.connect(lambda: self.un_reserve_table(self.tables[8], self.text_label[8]))

        self.table_info_push_buttons[0].clicked.connect(lambda: self.show_table_info_dialog(self.tables[0]))
        self.table_info_push_buttons[1].clicked.connect(lambda: self.show_table_info_dialog(self.tables[1]))
        self.table_info_push_buttons[2].clicked.connect(lambda: self.show_table_info_dialog(self.tables[2]))
        self.table_info_push_buttons[3].clicked.connect(lambda: self.show_table_info_dialog(self.tables[3]))
        self.table_info_push_buttons[4].clicked.connect(lambda: self.show_table_info_dialog(self.tables[4]))
        self.table_info_push_buttons[5].clicked.connect(lambda: self.show_table_info_dialog(self.tables[5]))
        self.table_info_push_buttons[6].clicked.connect(lambda: self.show_table_info_dialog(self.tables[6]))
        self.table_info_push_buttons[7].clicked.connect(lambda: self.show_table_info_dialog(self.tables[7]))
        self.table_info_push_buttons[8].clicked.connect(lambda: self.show_table_info_dialog(self.tables[8]))
        self.pushButton_11.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Table Reservation"))
        self.groupBox.setTitle(_translate("MainWindow", "Table 1"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_21.setText(_translate("MainWindow", "Table Info"))
        self.pushButton_12.setText(_translate("MainWindow", "Reserve"))
        self.pushButton.setText(_translate("MainWindow", "Un Reserve"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Table 2"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_4.setText(_translate("MainWindow", "Table Info"))
        self.pushButton_15.setText(_translate("MainWindow", "Reserve"))
        self.pushButton_22.setText(_translate("MainWindow", "Un Reserve"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Table 3"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_23.setText(_translate("MainWindow", "Table Info"))
        self.pushButton_20.setText(_translate("MainWindow", "Reserve"))
        self.pushButton_7.setText(_translate("MainWindow", "Un Reserve"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Table 4"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_2.setText(_translate("MainWindow", "Table Info"))
        self.pushButton_13.setText(_translate("MainWindow", "Reserve"))
        self.pushButton_24.setText(_translate("MainWindow", "Un Reserve"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Table 5"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_5.setText(_translate("MainWindow", "Table Info"))
        self.pushButton_16.setText(_translate("MainWindow", "Reserve"))
        self.pushButton_29.setText(_translate("MainWindow", "Un Reserve"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Table 6"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_8.setText(_translate("MainWindow", "Table Info"))
        self.pushButton_19.setText(_translate("MainWindow", "Reserve"))
        self.pushButton_28.setText(_translate("MainWindow", "Un Reserve"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Table 7"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_3.setText(_translate("MainWindow", "Table Info"))
        self.pushButton_14.setText(_translate("MainWindow", "Reserve"))
        self.pushButton_25.setText(_translate("MainWindow", "Un Reserve"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Table 8"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_6.setText(_translate("MainWindow", "Table Info"))
        self.pushButton_17.setText(_translate("MainWindow", "Reserve"))
        self.pushButton_26.setText(_translate("MainWindow", "Un Reserve"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Table 9"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_9.setText(_translate("MainWindow", "Table Info"))
        self.pushButton_18.setText(_translate("MainWindow", "Reserve"))
        self.pushButton_27.setText(_translate("MainWindow", "Un Reserve"))
        self.pushButton_10.setText(_translate("MainWindow", "Back To Main Menu"))
        self.pushButton_11.setText(_translate("MainWindow", "Close"))
        self.init_labels()


    def init_labels(self):
        for x in range(9):
            self.text_label[x].setFont(self.font)
            if self.tables[x].status == 'Reserved':
                self.text_label[x].setText('Reserved')
                self.text_label[x].setStyleSheet("color: rgb(255, 0, 0);")
            else:
                self.text_label[x].setText('Not Reserved')
                self.text_label[x].setStyleSheet("color: rgb(0, 170, 0);")


    def show_table_info_dialog(self,table):
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(Dialog)
        ui.tableWidget.setItem(0, 0, QTableWidgetItem('Table Number'))
        ui.tableWidget.setItem(0, 1, QTableWidgetItem(str(table.number)))
        ui.tableWidget.setItem(1, 0, QTableWidgetItem('Number Of Chairs'))
        ui.tableWidget.setItem(1, 1, QTableWidgetItem(str(table.no_of_chairs)))
        ui.tableWidget.setItem(2, 0, QTableWidgetItem('Status'))
        ui.tableWidget.setItem(2, 1, QTableWidgetItem(str(table.status)))
        if table.status == 'Reserved':
            ui.tableWidget.insertRow(3)
            ui.tableWidget.setItem(3, 0, QTableWidgetItem('Reserver Name'))
            ui.tableWidget.setItem(3, 1, QTableWidgetItem(str(table.reserver_name)))
            ui.tableWidget.insertRow(4)
            ui.tableWidget.setItem(4, 0, QTableWidgetItem('Reserver Phone'))
            ui.tableWidget.setItem(4, 1, QTableWidgetItem(str(table.reserver_phone)))

        Dialog.show()
        Dialog.exec_()

    def get_reserver_data(self,table, name, phone):
        table.reserver_name = name
        table.reserver_phone = phone

    def enter_reserver_data(self,table):
        Dialog = QtWidgets.QDialog()
        reserver_data_ui = Ui_Dialog3()
        reserver_data_ui.setupUi(Dialog)
        reserver_data_ui.pushButton.clicked.connect(
            lambda: self.get_reserver_data(table, reserver_data_ui.lineEdit.displayText(),
                                      reserver_data_ui.lineEdit_2.displayText()))
        reserver_data_ui.pushButton_2.clicked.connect(Dialog.close)
        Dialog.show()
        Dialog.exec_()

    def reserve_table(self,table, text_label):
        if table.status == 'Not Reserved':
            self.enter_reserver_data(table)
            if table.reserver_name and table.reserver_phone:
                table.status = 'Reserved'
                text_label.setText('Reserved')
                text_label.setStyleSheet("color: rgb(255, 0, 0);")


        else:
            # an error dialog to be out
            Dialog = QtWidgets.QDialog()
            warning_ui = Ui_Dialog2()
            warning_ui.setupUi(Dialog)
            Dialog.show()
            Dialog.exec_()

    def un_reserve_table(self,table, text_label):
        if table.status == 'Reserved':
            table.status = 'Not Reserved'
            table.reserver_phone = ''
            table.reserver_name = ''
            text_label.setText('Not Reserved')
            text_label.setStyleSheet("color: rgb(0, 170, 0);")







if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui =Table_Rerservation()
    ui.setupUi(MainWindow)
    MainWindow.show()
    print(ui.text_label)
    sys.exit(app.exec_())
